# Generated by Django 4.1.1 on 2023-03-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
