# Generated by Django 4.1.3 on 2023-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
